modLoader="javafml"
loaderVersion="[10,)"
issueTrackerURL="https://github.com/RobertSkalko/Mine-and-Slash/issues"
logoFile="logo.png"
[[mods]]
modId="mmorpg"
version="2.8.0"
displayName="Mine and Slash"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mine-and-slash-reloaded"
authors="robertx22(main author), matpac(artist)"
description='''
Turn Minecraft Into a hack and slash looter!
'''
[[dependencies.mmorpg]]
    modId="forge"
    mandatory=true
    versionRange="[28.1.6,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mmorpg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
	side="BOTH"
[[dependencies.mmorpg]]
    modId="curios" 
    mandatory=true 
    versionRange="[FORGE-1.14.4-1.0,)" 
    ordering="NONE"
    side="BOTH"
	